export const validPersonNames: string[] = [
  "Obi-Wan Kenobi",
  "Wilhuff Tarkin",
  "Chewbacca",
  "Han Solo",
  "Greedo",
  "Jabba Desilijic Tiure",
  "Wedge Antilles",
  "Jek Tono Porkins",
  "Yoda",
  "Palpatine",
  "Obi-Wan Kenobi",
  "Wilhuff Tarkin",
  "Chewbacca",
  "Han Solo",
  "Greedo",
  "Jabba Desilijic Tiure",
  "Wedge Antilles",
  "Jek Tono Porkins",
  "Yoda",
  "Palpatine",
  "Boba Fett",
  "IG-88",
  "Bossk",
  "Lando Calrissian",
  "Lobot",
  "Ackbar",
  "Mon Mothma",
  "Arvel Crynyd",
  "Wicket Systri Warrick",
  "Nien Nunb",
  "Qui-Gon Jinn",
  "Nute Gunray",
  "Finis Valorum",
  "Padmé Amidala",
  "Jar Jar Binks",
  "Roos Tarpals",
  "Rugor Nass",
  "Ric Olié",
  "Luke Skywalker",
  "C-3PO",
  "R2-D2",
  "Darth Vader",
  "Leia Organa",
  "Owen Lars",
  "Beru Whitesun Lars",
  "R5-D4",
  "Biggs Darklighter",
  "Watto",
  "Sebulba",
  "Quarsh Panaka",
  "Shmi Skywalker",
  "Darth Maul",
  "Bib Fortuna",
  "Ayla Secura",
  "Ratts Tyerel",
  "Dud Bolt",
  "Anakin Skywalker",
  "Gasgano",
  "Ben Quadinaros",
  "Mace Windu",
  "Ki-Adi-Mundi",
  "Kit Fisto",
  "Eeth Koth",
  "Adi Gallia",
  "Saesee Tiin",
  "Yarael Poof",
  "Plo Koon",
  "Mas Amedda",
  "Gregar Typho",
  "Cordé",
  "Cliegg Lars",
  "Poggle the Lesser",
  "Luminara Unduli",
  "Barriss Offee",
  "Dormé",
  "Dooku",
  "Bail Prestor Organa",
  "Jango Fett",
  "Zam Wesell",
  "Dexter Jettster",
  "Lama Su",
  "Taun We",
  "Jocasta Nu",
  "R4-P17",
  "Wat Tambor",
  "San Hill",
  "Shaak Ti",
  "Grievous",
  "Tarfful",
  "Raymus Antilles",
  "Sly Moore",
  "Tion Medon",
];

export const validFilms = [
  "A New Hope",
  "The Empire Strikes Back",
  "Return of the Jedi",
  "The Phantom Menace",
  "Attack of the Clones",
  "Revenge of the Sith",
];
